site_name: Drone Project — UCB Lyon 1
theme:
  name: material
  palette:
    # primary: indigo
    primary: orange
    # accent: orange

nav:
  - Home: index.md
  - Hardware: hardware.md
  - ROS 2 Stack: ros2.md
  - SE3 Controller: controller.md
